name: Weekly Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '42 10 * * 0' # Every Sunday at 10:42

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    container: node:16
    environment: Production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Sync
        run: yarn sync
        env:
          SLACK_XOXC: ${{ secrets.SLACK_XOXC }}
          SLACK_XOXD: ${{ secrets.SLACK_XOXD }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}